### PR TITLE
Removing problematic preventDefault lines

### LINKED ISSUE #38: preventDefault warning
svgpan.js:153 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

### PR DESCRIPTION
**Pull request by aphelionz**
Removing the lines that were causing the `preventDefault` warning (now an error!) Fixes #38

### CODE REVIEW

**Comment by aleofreddi** [comment]
Hi Mark,
thanks for the PR. I'm wondering if removing these lines cause a regression on older versions or other browsers. What do you think?

**Comment by aphelionz** [comment]
Good question! I can test with browserstack if we can get a public demo updated.

**Comment by aleofreddi** [comment]
I've noticed there are other `preventDefault` usages around, we should fix the issue for all of them

**Comment by aleofreddi** [comment]
Any news on this? Looking around I've found this one as proposed solution:

```
(passiveSupported && (active || el == window.document || el == window.document.body || el == window)) ? 
    el.addEventListener(name, fn, { passive: false, capture: bubble }) 
    : el.addEventListener(name, fn, bubble || false);
```

**Comment by aphelionz** [comment]
I admit I haven't had much time to look at this since the original PR... your snippet looks good, I bet that can be abstracted to a function and re-used

**Pull request closed without merging**
